const path = require("path");
require("dotenv").config({ path: path.join(__dirname, "../.env") });
const mongoose = require("mongoose");
const MarketData = require("../models/MarketData");
const User = require("../models/User");

const MARKET_DATA = [
  {
    careerId: "software_engineer",
    title: "Software Engineer",
    category: "Technology",
    description:
      "Design, develop, and maintain software systems and applications.",
    demandLevel: "Very High",
    averageSalary: { entry: 65000, mid: 105000, senior: 155000 },
    growthRate: 25,
    jobOpenings: 450000,
    trending: true,
    remote: true,
    topSkills: [
      { name: "Python", importance: 9 },
      { name: "JavaScript", importance: 9 },
      { name: "Data Structures", importance: 8 },
      { name: "Git", importance: 8 },
      { name: "SQL", importance: 7 },
      { name: "System Design", importance: 8 },
    ],
    companies: ["Google", "Microsoft", "Amazon", "Meta", "Apple"],
  },
  {
    careerId: "data_scientist",
    title: "Data Scientist",
    category: "Data & AI",
    description:
      "Analyze complex data sets to help companies make data-driven decisions.",
    demandLevel: "Very High",
    averageSalary: { entry: 70000, mid: 115000, senior: 165000 },
    growthRate: 36,
    jobOpenings: 300000,
    trending: true,
    remote: true,
    topSkills: [
      { name: "Python", importance: 10 },
      { name: "Machine Learning", importance: 10 },
      { name: "Statistics", importance: 9 },
      { name: "SQL", importance: 8 },
      { name: "TensorFlow", importance: 7 },
      { name: "Data Visualization", importance: 8 },
    ],
    companies: ["Netflix", "Airbnb", "LinkedIn", "Uber", "Spotify"],
  },
  {
    careerId: "web_developer",
    title: "Full Stack Web Developer",
    category: "Technology",
    description:
      "Build and maintain web applications across the full technology stack.",
    demandLevel: "High",
    averageSalary: { entry: 55000, mid: 90000, senior: 135000 },
    growthRate: 23,
    jobOpenings: 180000,
    trending: false,
    remote: true,
    topSkills: [
      { name: "React", importance: 9 },
      { name: "Node.js", importance: 9 },
      { name: "CSS", importance: 8 },
      { name: "MongoDB", importance: 7 },
      { name: "TypeScript", importance: 8 },
      { name: "REST APIs", importance: 9 },
    ],
    companies: ["Shopify", "Stripe", "Vercel", "Netlify", "Atlassian"],
  },
  {
    careerId: "devops_engineer",
    title: "DevOps Engineer",
    category: "Technology",
    description:
      "Bridge software development and IT operations for faster, reliable delivery.",
    demandLevel: "Very High",
    averageSalary: { entry: 70000, mid: 115000, senior: 160000 },
    growthRate: 22,
    jobOpenings: 140000,
    trending: true,
    remote: true,
    topSkills: [
      { name: "Docker", importance: 10 },
      { name: "Kubernetes", importance: 9 },
      { name: "CI/CD", importance: 10 },
      { name: "Linux", importance: 9 },
      { name: "AWS", importance: 9 },
      { name: "Terraform", importance: 8 },
    ],
    companies: ["HashiCorp", "Red Hat", "GitLab", "GitHub", "Cloudflare"],
  },
  {
    careerId: "cybersecurity_analyst",
    title: "Cybersecurity Analyst",
    category: "Security",
    description:
      "Protect organizations from digital threats and security breaches.",
    demandLevel: "Very High",
    averageSalary: { entry: 60000, mid: 100000, senior: 148000 },
    growthRate: 35,
    jobOpenings: 200000,
    trending: true,
    remote: false,
    topSkills: [
      { name: "Network Security", importance: 10 },
      { name: "Python", importance: 8 },
      { name: "Linux", importance: 9 },
      { name: "SIEM", importance: 7 },
      { name: "Penetration Testing", importance: 8 },
      { name: "Risk Assessment", importance: 9 },
    ],
    companies: [
      "CrowdStrike",
      "Palo Alto Networks",
      "Cisco",
      "IBM Security",
      "Fortinet",
    ],
  },
  {
    careerId: "product_manager",
    title: "Product Manager",
    category: "Business",
    description:
      "Define product vision and drive cross-functional teams to deliver value.",
    demandLevel: "High",
    averageSalary: { entry: 75000, mid: 125000, senior: 175000 },
    growthRate: 19,
    jobOpenings: 90000,
    trending: false,
    remote: true,
    topSkills: [
      { name: "Agile", importance: 9 },
      { name: "Data Analysis", importance: 8 },
      { name: "Communication", importance: 10 },
      { name: "UX/UI", importance: 7 },
      { name: "Roadmapping", importance: 9 },
      { name: "Leadership", importance: 10 },
    ],
    companies: ["Google", "Apple", "Airbnb", "Slack", "Zoom"],
  },
  {
    careerId: "ux_designer",
    title: "UX/UI Designer",
    category: "Design",
    description:
      "Create intuitive, engaging user experiences for digital products.",
    demandLevel: "High",
    averageSalary: { entry: 55000, mid: 90000, senior: 130000 },
    growthRate: 16,
    jobOpenings: 95000,
    trending: false,
    remote: true,
    topSkills: [
      { name: "Figma", importance: 10 },
      { name: "User Research", importance: 9 },
      { name: "Prototyping", importance: 9 },
      { name: "Wireframing", importance: 8 },
      { name: "Design Systems", importance: 8 },
      { name: "CSS", importance: 7 },
    ],
    companies: ["Adobe", "Figma", "InVision", "Spotify", "Pinterest"],
  },
  {
    careerId: "mobile_developer",
    title: "Mobile App Developer",
    category: "Technology",
    description: "Build native and cross-platform mobile applications.",
    demandLevel: "High",
    averageSalary: { entry: 65000, mid: 105000, senior: 148000 },
    growthRate: 22,
    jobOpenings: 130000,
    trending: true,
    remote: true,
    topSkills: [
      { name: "React Native", importance: 9 },
      { name: "Swift", importance: 8 },
      { name: "Kotlin", importance: 8 },
      { name: "Flutter", importance: 8 },
      { name: "REST APIs", importance: 9 },
      { name: "Firebase", importance: 7 },
    ],
    companies: ["Apple", "Google", "Samsung", "Snap", "TikTok"],
  },
  {
    careerId: "cloud_architect",
    title: "Cloud Architect",
    category: "Technology",
    description:
      "Design and oversee cloud computing strategies and infrastructure.",
    demandLevel: "Very High",
    averageSalary: { entry: 80000, mid: 135000, senior: 190000 },
    growthRate: 28,
    jobOpenings: 85000,
    trending: true,
    remote: true,
    topSkills: [
      { name: "AWS", importance: 10 },
      { name: "Azure", importance: 9 },
      { name: "Microservices", importance: 9 },
      { name: "Security", importance: 9 },
      { name: "Networking", importance: 8 },
      { name: "Terraform", importance: 8 },
    ],
    companies: ["AWS", "Microsoft Azure", "Google Cloud", "Oracle", "IBM"],
  },
  {
    careerId: "ai_engineer",
    title: "AI/ML Engineer",
    category: "Data & AI",
    description:
      "Design, build, and deploy AI and machine learning systems at scale.",
    demandLevel: "Very High",
    averageSalary: { entry: 85000, mid: 140000, senior: 200000 },
    growthRate: 40,
    jobOpenings: 110000,
    trending: true,
    remote: true,
    topSkills: [
      { name: "Python", importance: 10 },
      { name: "TensorFlow", importance: 9 },
      { name: "PyTorch", importance: 9 },
      { name: "MLOps", importance: 8 },
      { name: "Deep Learning", importance: 10 },
      { name: "Mathematics", importance: 9 },
    ],
    companies: ["OpenAI", "DeepMind", "NVIDIA", "Anthropic", "Hugging Face"],
  },
  {
    careerId: "data_analyst",
    title: "Data Analyst",
    category: "Data & AI",
    description:
      "Collect, process, and analyze data to generate actionable business insights.",
    demandLevel: "High",
    averageSalary: { entry: 50000, mid: 78000, senior: 100000 },
    growthRate: 23,
    jobOpenings: 240000,
    trending: true,
    remote: true,
    topSkills: [
      { name: "SQL", importance: 10 },
      { name: "Excel", importance: 9 },
      { name: "Python", importance: 8 },
      { name: "Tableau", importance: 8 },
      { name: "Data Visualization", importance: 9 },
      { name: "Statistics", importance: 8 },
    ],
    companies: ["Deloitte", "Accenture", "IBM", "Salesforce", "McKinsey"],
  },
  {
    careerId: "blockchain_developer",
    title: "Blockchain Developer",
    category: "Technology",
    description:
      "Build decentralized applications and smart contracts on blockchain platforms.",
    demandLevel: "Medium",
    averageSalary: { entry: 80000, mid: 130000, senior: 180000 },
    growthRate: 30,
    jobOpenings: 32000,
    trending: true,
    remote: true,
    topSkills: [
      { name: "Solidity", importance: 10 },
      { name: "Web3.js", importance: 9 },
      { name: "JavaScript", importance: 8 },
      { name: "Cryptography", importance: 8 },
      { name: "Smart Contracts", importance: 10 },
      { name: "Ethereum", importance: 9 },
    ],
    companies: ["Coinbase", "Binance", "ConsenSys", "Chainlink", "Polygon"],
  },

  // ── MEDICAL & HEALTH ────────────────────────────────────────────────────────
  {
    careerId: "physician",
    title: "Physician / Medical Doctor",
    category: "Medical & Health",
    description:
      "Diagnose and treat illnesses, combining scientific knowledge with compassionate patient care.",
    demandLevel: "Very High",
    averageSalary: { entry: 90000, mid: 220000, senior: 350000 },
    growthRate: 13,
    jobOpenings: 320000,
    trending: true,
    remote: false,
    topSkills: [
      { name: "Clinical Diagnosis", importance: 10 },
      { name: "Patient Care", importance: 10 },
      { name: "Pharmacology", importance: 9 },
      { name: "Anatomy", importance: 9 },
      { name: "Medical Ethics", importance: 8 },
      { name: "Communication", importance: 9 },
    ],
    companies: [
      "Mayo Clinic",
      "Johns Hopkins",
      "Cleveland Clinic",
      "Kaiser Permanente",
      "Aetna",
    ],
  },
  {
    careerId: "nurse",
    title: "Registered Nurse",
    category: "Medical & Health",
    description:
      "Provide and coordinate patient care and offer advice and support to patients and families.",
    demandLevel: "Very High",
    averageSalary: { entry: 55000, mid: 82000, senior: 120000 },
    growthRate: 15,
    jobOpenings: 570000,
    trending: true,
    remote: false,
    topSkills: [
      { name: "Patient Care", importance: 10 },
      { name: "Clinical Assessment", importance: 10 },
      { name: "Medication Administration", importance: 9 },
      { name: "Critical Thinking", importance: 9 },
      { name: "Communication", importance: 9 },
      { name: "Electronic Health Records", importance: 7 },
    ],
    companies: [
      "HCA Healthcare",
      "Tenet Health",
      "CommonSpirit",
      "Ascension",
      "Mayo Clinic",
    ],
  },
  {
    careerId: "pharmacist",
    title: "Pharmacist",
    category: "Medical & Health",
    description:
      "Dispense medications, counsel patients on drug use, and collaborate with healthcare teams.",
    demandLevel: "High",
    averageSalary: { entry: 85000, mid: 118000, senior: 148000 },
    growthRate: 6,
    jobOpenings: 15000,
    trending: false,
    remote: false,
    topSkills: [
      { name: "Pharmacology", importance: 10 },
      { name: "Drug Interactions", importance: 10 },
      { name: "Patient Counseling", importance: 9 },
      { name: "Chemistry", importance: 8 },
      { name: "Regulatory Compliance", importance: 8 },
      { name: "Clinical Pharmacy", importance: 9 },
    ],
    companies: [
      "CVS Health",
      "Walgreens",
      "Express Scripts",
      "Rite Aid",
      "McKesson",
    ],
  },
  {
    careerId: "public_health_specialist",
    title: "Public Health Specialist",
    category: "Medical & Health",
    description:
      "Promote community health, design prevention programs, and analyze population health data.",
    demandLevel: "High",
    averageSalary: { entry: 50000, mid: 72000, senior: 100000 },
    growthRate: 14,
    jobOpenings: 65000,
    trending: true,
    remote: true,
    topSkills: [
      { name: "Epidemiology", importance: 10 },
      { name: "Biostatistics", importance: 9 },
      { name: "Data Analysis", importance: 8 },
      { name: "Public Health Policy", importance: 9 },
      { name: "Community Outreach", importance: 8 },
      { name: "Grant Writing", importance: 7 },
    ],
    companies: [
      "CDC",
      "WHO",
      "NIH",
      "UNICEF",
      "Johns Hopkins Bloomberg School",
    ],
  },
  {
    careerId: "medical_researcher",
    title: "Medical / Biomedical Researcher",
    category: "Medical & Health",
    description:
      "Conduct research to advance medical knowledge and develop new treatments.",
    demandLevel: "High",
    averageSalary: { entry: 60000, mid: 92000, senior: 130000 },
    growthRate: 17,
    jobOpenings: 48000,
    trending: true,
    remote: false,
    topSkills: [
      { name: "Research Methods", importance: 10 },
      { name: "Statistics", importance: 9 },
      { name: "Laboratory Techniques", importance: 9 },
      { name: "Scientific Writing", importance: 9 },
      { name: "Python", importance: 7 },
      { name: "Clinical Trials", importance: 8 },
    ],
    companies: ["Pfizer", "Johnson & Johnson", "Merck", "Novartis", "NIH"],
  },

  // ── FINANCE & ECONOMICS ─────────────────────────────────────────────────────
  {
    careerId: "financial_analyst",
    title: "Financial Analyst",
    category: "Finance & Economics",
    description:
      "Evaluate investment opportunities and financial data to guide business decisions.",
    demandLevel: "High",
    averageSalary: { entry: 60000, mid: 92000, senior: 130000 },
    growthRate: 9,
    jobOpenings: 96000,
    trending: false,
    remote: true,
    topSkills: [
      { name: "Financial Modeling", importance: 10 },
      { name: "Excel", importance: 10 },
      { name: "Valuation", importance: 9 },
      { name: "Accounting", importance: 8 },
      { name: "Python", importance: 7 },
      { name: "Bloomberg Terminal", importance: 8 },
    ],
    companies: [
      "Goldman Sachs",
      "JPMorgan",
      "Morgan Stanley",
      "BlackRock",
      "Fidelity",
    ],
  },
  {
    careerId: "investment_banker",
    title: "Investment Banker",
    category: "Finance & Economics",
    description:
      "Advise corporations on mergers, acquisitions, IPOs, and capital raising strategies.",
    demandLevel: "High",
    averageSalary: { entry: 90000, mid: 180000, senior: 300000 },
    growthRate: 10,
    jobOpenings: 48000,
    trending: true,
    remote: false,
    topSkills: [
      { name: "Financial Modeling", importance: 10 },
      { name: "M&A Analysis", importance: 9 },
      { name: "Valuation", importance: 10 },
      { name: "Excel", importance: 9 },
      { name: "Deal Structuring", importance: 9 },
      { name: "Presentation Skills", importance: 8 },
    ],
    companies: [
      "Goldman Sachs",
      "Morgan Stanley",
      "JPMorgan",
      "Lazard",
      "Evercore",
    ],
  },
  {
    careerId: "accountant",
    title: "Accountant / CPA",
    category: "Finance & Economics",
    description:
      "Prepare and examine financial records, ensure accuracy, and maintain compliance with laws.",
    demandLevel: "High",
    averageSalary: { entry: 50000, mid: 75000, senior: 110000 },
    growthRate: 7,
    jobOpenings: 140000,
    trending: false,
    remote: true,
    topSkills: [
      { name: "Bookkeeping", importance: 9 },
      { name: "Tax Preparation", importance: 9 },
      { name: "Financial Reporting", importance: 10 },
      { name: "Excel", importance: 9 },
      { name: "QuickBooks", importance: 8 },
      { name: "Auditing", importance: 8 },
    ],
    companies: ["Deloitte", "PwC", "EY", "KPMG", "BDO"],
  },
  {
    careerId: "risk_manager",
    title: "Risk Manager",
    category: "Finance & Economics",
    description:
      "Identify, assess, and mitigate financial and operational risks within organizations.",
    demandLevel: "High",
    averageSalary: { entry: 70000, mid: 110000, senior: 150000 },
    growthRate: 11,
    jobOpenings: 42000,
    trending: false,
    remote: true,
    topSkills: [
      { name: "Risk Assessment", importance: 10 },
      { name: "Financial Analysis", importance: 9 },
      { name: "Statistics", importance: 9 },
      { name: "Compliance", importance: 8 },
      { name: "Python", importance: 7 },
      { name: "Scenario Analysis", importance: 8 },
    ],
    companies: [
      "HSBC",
      "Citigroup",
      "Bank of America",
      "Deutsche Bank",
      "Marsh McLennan",
    ],
  },

  // ── ARTS & HUMANITIES ───────────────────────────────────────────────────────
  {
    careerId: "graphic_designer",
    title: "Graphic Designer",
    category: "Arts & Humanities",
    description:
      "Create visual content to communicate messages through typography, imagery, and layout.",
    demandLevel: "High",
    averageSalary: { entry: 40000, mid: 62000, senior: 95000 },
    growthRate: 11,
    jobOpenings: 80000,
    trending: false,
    remote: true,
    topSkills: [
      { name: "Adobe Photoshop", importance: 10 },
      { name: "Adobe Illustrator", importance: 10 },
      { name: "Typography", importance: 9 },
      { name: "Color Theory", importance: 8 },
      { name: "Branding", importance: 8 },
      { name: "Figma", importance: 8 },
    ],
    companies: ["Adobe", "Canva", "BBDO", "Ogilvy", "Pentagram"],
  },
  {
    careerId: "content_writer",
    title: "Content Writer / Copywriter",
    category: "Arts & Humanities",
    description:
      "Create compelling written content for digital platforms, marketing, and brand communication.",
    demandLevel: "High",
    averageSalary: { entry: 35000, mid: 58000, senior: 90000 },
    growthRate: 9,
    jobOpenings: 63000,
    trending: false,
    remote: true,
    topSkills: [
      { name: "Writing", importance: 10 },
      { name: "SEO", importance: 9 },
      { name: "Content Strategy", importance: 9 },
      { name: "Research", importance: 8 },
      { name: "Storytelling", importance: 9 },
      { name: "Editing", importance: 8 },
    ],
    companies: [
      "HubSpot",
      "BuzzFeed",
      "The New York Times",
      "Contently",
      "Copyblogger",
    ],
  },
  {
    careerId: "journalist",
    title: "Journalist / Reporter",
    category: "Arts & Humanities",
    description:
      "Investigate, report, and present news stories across print, digital, broadcast, and multimedia platforms.",
    demandLevel: "Medium",
    averageSalary: { entry: 35000, mid: 55000, senior: 85000 },
    growthRate: 3,
    jobOpenings: 25000,
    trending: false,
    remote: true,
    topSkills: [
      { name: "Writing", importance: 10 },
      { name: "Investigative Research", importance: 10 },
      { name: "Interviewing", importance: 9 },
      { name: "Storytelling", importance: 9 },
      { name: "Media Ethics", importance: 8 },
      { name: "Social Media", importance: 7 },
    ],
    companies: ["Reuters", "BBC", "AP News", "The Guardian", "CNN"],
  },
  {
    careerId: "teacher_educator",
    title: "Teacher / Educator",
    category: "Education",
    description:
      "Educate students at various levels, developing curriculum and engaging learning environments.",
    demandLevel: "High",
    averageSalary: { entry: 35000, mid: 55000, senior: 80000 },
    growthRate: 7,
    jobOpenings: 230000,
    trending: false,
    remote: false,
    topSkills: [
      { name: "Curriculum Development", importance: 10 },
      { name: "Classroom Management", importance: 9 },
      { name: "Communication", importance: 10 },
      { name: "Assessment", importance: 8 },
      { name: "Lesson Planning", importance: 9 },
      { name: "EdTech", importance: 7 },
    ],
    companies: [
      "Pearson",
      "Khan Academy",
      "Coursera",
      "Duolingo",
      "KIPP Foundation",
    ],
  },
  {
    careerId: "translator",
    title: "Translator / Interpreter",
    category: "Arts & Humanities",
    description:
      "Convert written or spoken content between languages, preserving meaning and cultural nuance.",
    demandLevel: "Medium",
    averageSalary: { entry: 40000, mid: 58000, senior: 90000 },
    growthRate: 6,
    jobOpenings: 22000,
    trending: false,
    remote: true,
    topSkills: [
      { name: "Bilingualism", importance: 10 },
      { name: "Cultural Awareness", importance: 9 },
      { name: "Writing", importance: 9 },
      { name: "Research", importance: 8 },
      { name: "CAT Tools", importance: 7 },
      { name: "Attention to Detail", importance: 9 },
    ],
    companies: [
      "TransPerfect",
      "Lionbridge",
      "SDL",
      "UN Language Services",
      "Berlitz",
    ],
  },

  // ── ENGINEERING ─────────────────────────────────────────────────────────────
  {
    careerId: "civil_engineer",
    title: "Civil Engineer",
    category: "Engineering",
    description:
      "Design, build, and maintain infrastructure such as roads, bridges, and water systems.",
    demandLevel: "High",
    averageSalary: { entry: 60000, mid: 90000, senior: 130000 },
    growthRate: 8,
    jobOpenings: 115000,
    trending: false,
    remote: false,
    topSkills: [
      { name: "AutoCAD", importance: 10 },
      { name: "Structural Analysis", importance: 10 },
      { name: "Project Management", importance: 9 },
      { name: "Mathematics", importance: 9 },
      { name: "Building Codes", importance: 8 },
      { name: "BIM", importance: 8 },
    ],
    companies: ["AECOM", "Jacobs", "Turner Construction", "Bechtel", "WSP"],
  },
  {
    careerId: "mechanical_engineer",
    title: "Mechanical Engineer",
    category: "Engineering",
    description:
      "Design and develop mechanical systems, machines, and devices from concept to production.",
    demandLevel: "High",
    averageSalary: { entry: 62000, mid: 95000, senior: 130000 },
    growthRate: 7,
    jobOpenings: 90000,
    trending: false,
    remote: false,
    topSkills: [
      { name: "CAD Design", importance: 10 },
      { name: "Thermodynamics", importance: 9 },
      { name: "Mechanics", importance: 10 },
      { name: "Materials Science", importance: 8 },
      { name: "SolidWorks", importance: 9 },
      { name: "MATLAB", importance: 7 },
    ],
    companies: ["Boeing", "Tesla", "Caterpillar", "Honeywell", "GE"],
  },
  {
    careerId: "electrical_engineer",
    title: "Electrical Engineer",
    category: "Engineering",
    description:
      "Design, develop, and test electrical systems and components for consumer and industrial applications.",
    demandLevel: "High",
    averageSalary: { entry: 65000, mid: 102000, senior: 140000 },
    growthRate: 11,
    jobOpenings: 80000,
    trending: true,
    remote: false,
    topSkills: [
      { name: "Circuit Design", importance: 10 },
      { name: "Electronics", importance: 10 },
      { name: "MATLAB", importance: 8 },
      { name: "Signal Processing", importance: 9 },
      { name: "PCB Design", importance: 8 },
      { name: "Embedded Systems", importance: 8 },
    ],
    companies: ["Intel", "Qualcomm", "Texas Instruments", "Siemens", "ABB"],
  },
  {
    careerId: "environmental_engineer",
    title: "Environmental Engineer",
    category: "Engineering",
    description:
      "Apply engineering principles to solve environmental problems, including pollution control.",
    demandLevel: "High",
    averageSalary: { entry: 58000, mid: 88000, senior: 120000 },
    growthRate: 12,
    jobOpenings: 42000,
    trending: true,
    remote: false,
    topSkills: [
      { name: "Environmental Regulations", importance: 10 },
      { name: "Data Analysis", importance: 8 },
      { name: "Project Management", importance: 9 },
      { name: "Chemistry", importance: 9 },
      { name: "GIS", importance: 8 },
      { name: "Water Treatment", importance: 8 },
    ],
    companies: ["AECOM", "Tetra Tech", "ERM Group", "Burns & McDonnell", "EPA"],
  },

  // ── BUSINESS & MANAGEMENT ───────────────────────────────────────────────────
  {
    careerId: "marketing_manager",
    title: "Marketing Manager",
    category: "Business & Management",
    description:
      "Plan and execute marketing strategies and brand initiatives to drive growth.",
    demandLevel: "High",
    averageSalary: { entry: 55000, mid: 95000, senior: 130000 },
    growthRate: 10,
    jobOpenings: 100000,
    trending: true,
    remote: true,
    topSkills: [
      { name: "Marketing Strategy", importance: 10 },
      { name: "Digital Marketing", importance: 9 },
      { name: "SEO/SEM", importance: 9 },
      { name: "Analytics", importance: 8 },
      { name: "Content Creation", importance: 8 },
      { name: "Brand Management", importance: 9 },
    ],
    companies: ["Procter & Gamble", "Unilever", "HubSpot", "Google", "Meta"],
  },
  {
    careerId: "human_resources_manager",
    title: "Human Resources Manager",
    category: "Business & Management",
    description:
      "Oversee recruitment, employee relations, benefits, and organizational development.",
    demandLevel: "High",
    averageSalary: { entry: 55000, mid: 85000, senior: 120000 },
    growthRate: 9,
    jobOpenings: 72000,
    trending: false,
    remote: true,
    topSkills: [
      { name: "Recruitment", importance: 10 },
      { name: "Employee Relations", importance: 9 },
      { name: "HR Policy", importance: 9 },
      { name: "Communication", importance: 10 },
      { name: "Conflict Resolution", importance: 8 },
      { name: "People Analytics", importance: 7 },
    ],
    companies: ["IBM", "Accenture", "McKinsey", "Deloitte", "Workday"],
  },

  // ── LAW ─────────────────────────────────────────────────────────────────────
  {
    careerId: "lawyer",
    title: "Lawyer / Solicitor",
    category: "Law",
    description:
      "Advise clients on legal matters, draft contracts, and represent them in court or negotiations.",
    demandLevel: "High",
    averageSalary: { entry: 65000, mid: 130000, senior: 250000 },
    growthRate: 9,
    jobOpenings: 55000,
    trending: false,
    remote: false,
    topSkills: [
      { name: "Legal Research", importance: 10 },
      { name: "Legal Writing", importance: 10 },
      { name: "Argumentation", importance: 9 },
      { name: "Contract Law", importance: 9 },
      { name: "Critical Thinking", importance: 9 },
      { name: "Negotiation", importance: 8 },
    ],
    companies: [
      "Baker McKenzie",
      "Latham & Watkins",
      "DLA Piper",
      "Clifford Chance",
      "Allen & Overy",
    ],
  },
];

const seedDB = async () => {
  try {
    await mongoose.connect(
      process.env.MONGO_URI || "mongodb://localhost:27017/ai_career_guidance",
    );
    console.log("Connected to MongoDB");

    // Seed market data
    for (const data of MARKET_DATA) {
      await MarketData.findOneAndUpdate(
        { careerId: data.careerId },
        { $set: data },
        { upsert: true },
      );
    }
    console.log(`✅ Seeded ${MARKET_DATA.length} career market records`);

    // Create default admin
    const adminExists = await User.findOne({
      email: "admin@careerguidance.ai",
    });
    if (!adminExists) {
      await User.create({
        name: "Admin User",
        email: "admin@careerguidance.ai",
        password: "Admin@1234",
        role: "admin",
      });
      console.log(
        "✅ Created default admin: admin@careerguidance.ai / Admin@1234",
      );
    }

    console.log("✅ Database seeding complete");
    process.exit(0);
  } catch (error) {
    console.error("Seeding failed:", error);
    process.exit(1);
  }
};

seedDB();
