const path = require("path");
require("dotenv").config({ path: path.join(__dirname, "../.env") });
const mongoose = require("mongoose");
const MarketData = require("../models/MarketData");
const User = require("../models/User");

const MARKET_DATA = [
  // ── TECHNOLOGY ──────────────────────────────────────────────────────────────
  {
    careerId: "software_engineer",
    title: "Software Engineer",
    category: "Technology",
    description:
      "Design, develop, and maintain software systems and applications.",
    demandLevel: "Very High",
    averageSalary: { entry: 1800000, mid: 5400000, senior: 14400000 },
    growthRate: 25,
    jobOpenings: 8000,
    trending: true,
    remote: true,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Python", importance: 9 },
      { name: "JavaScript", importance: 9 },
      { name: "Data Structures", importance: 8 },
      { name: "Git", importance: 8 },
      { name: "SQL", importance: 7 },
      { name: "System Design", importance: 8 },
    ],
    companies: ["Flutterwave", "Paystack", "Andela", "Interswitch", "SystemSpecs"],
  },
  {
    careerId: "data_scientist",
    title: "Data Scientist",
    category: "Data & AI",
    description:
      "Analyze complex data sets to help companies make data-driven decisions.",
    demandLevel: "Very High",
    averageSalary: { entry: 2400000, mid: 7200000, senior: 18000000 },
    growthRate: 36,
    jobOpenings: 2500,
    trending: true,
    remote: true,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Python", importance: 10 },
      { name: "Machine Learning", importance: 10 },
      { name: "Statistics", importance: 9 },
      { name: "SQL", importance: 8 },
      { name: "TensorFlow", importance: 7 },
      { name: "Data Visualization", importance: 8 },
    ],
    companies: ["Konga", "Jumia", "PiggyVest", "Cowrywise", "TeamApt"],
  },
  {
    careerId: "web_developer",
    title: "Full Stack Web Developer",
    category: "Technology",
    description:
      "Build and maintain web applications across the full technology stack.",
    demandLevel: "High",
    averageSalary: { entry: 1500000, mid: 4200000, senior: 9600000 },
    growthRate: 23,
    jobOpenings: 6000,
    trending: false,
    remote: true,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "React", importance: 9 },
      { name: "Node.js", importance: 9 },
      { name: "CSS", importance: 8 },
      { name: "MongoDB", importance: 7 },
      { name: "TypeScript", importance: 8 },
      { name: "REST APIs", importance: 9 },
    ],
    companies: ["Softcom", "Eden Life", "Buypower", "Releaf", "ThriveAgric"],
  },
  {
    careerId: "devops_engineer",
    title: "DevOps Engineer",
    category: "Technology",
    description:
      "Bridge software development and IT operations for faster, reliable delivery.",
    demandLevel: "Very High",
    averageSalary: { entry: 1800000, mid: 5400000, senior: 14400000 },
    growthRate: 22,
    jobOpenings: 3000,
    trending: true,
    remote: true,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Docker", importance: 10 },
      { name: "Kubernetes", importance: 9 },
      { name: "CI/CD", importance: 10 },
      { name: "Linux", importance: 9 },
      { name: "AWS", importance: 9 },
      { name: "Terraform", importance: 8 },
    ],
    companies: ["Flutterwave", "Interswitch", "Paystack", "Andela", "Moniepoint"],
  },
  {
    careerId: "cybersecurity_analyst",
    title: "Cybersecurity Analyst",
    category: "Security",
    description:
      "Protect organizations from digital threats and security breaches.",
    demandLevel: "Very High",
    averageSalary: { entry: 1800000, mid: 4800000, senior: 12000000 },
    growthRate: 35,
    jobOpenings: 4000,
    trending: true,
    remote: false,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Network Security", importance: 10 },
      { name: "Python", importance: 8 },
      { name: "Linux", importance: 9 },
      { name: "SIEM", importance: 7 },
      { name: "Penetration Testing", importance: 8 },
      { name: "Risk Assessment", importance: 9 },
    ],
    companies: [
      "Access Bank",
      "Zenith Bank",
      "GTBank",
      "MTN Nigeria",
      "Airtel Nigeria",
    ],
  },
  {
    careerId: "product_manager",
    title: "Product Manager",
    category: "Business & Management",
    description:
      "Define product vision and drive cross-functional teams to deliver value.",
    demandLevel: "High",
    averageSalary: { entry: 1800000, mid: 4200000, senior: 10800000 },
    growthRate: 19,
    jobOpenings: 2500,
    trending: false,
    remote: true,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Agile", importance: 9 },
      { name: "Data Analysis", importance: 8 },
      { name: "Communication", importance: 10 },
      { name: "UX/UI", importance: 7 },
      { name: "Roadmapping", importance: 9 },
      { name: "Leadership", importance: 10 },
    ],
    companies: ["Flutterwave", "Paystack", "Konga", "PiggyVest", "Cowrywise"],
  },
  {
    careerId: "ux_designer",
    title: "UX/UI Designer",
    category: "Design",
    description:
      "Create intuitive, engaging user experiences for digital products.",
    demandLevel: "High",
    averageSalary: { entry: 1200000, mid: 3000000, senior: 7200000 },
    growthRate: 16,
    jobOpenings: 3000,
    trending: false,
    remote: true,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Figma", importance: 10 },
      { name: "User Research", importance: 9 },
      { name: "Prototyping", importance: 9 },
      { name: "Wireframing", importance: 8 },
      { name: "Design Systems", importance: 8 },
      { name: "CSS", importance: 7 },
    ],
    companies: ["Noah's Ark", "X3M Ideas", "SO&U", "1D Creative", "Insight Publicis"],
  },
  {
    careerId: "mobile_developer",
    title: "Mobile App Developer",
    category: "Technology",
    description: "Build native and cross-platform mobile applications.",
    demandLevel: "High",
    averageSalary: { entry: 1500000, mid: 4200000, senior: 10800000 },
    growthRate: 22,
    jobOpenings: 4000,
    trending: true,
    remote: true,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "React Native", importance: 9 },
      { name: "Flutter", importance: 8 },
      { name: "Kotlin", importance: 8 },
      { name: "REST APIs", importance: 9 },
      { name: "Firebase", importance: 7 },
      { name: "Swift", importance: 6 },
    ],
    companies: ["Interswitch", "TeamApt", "Moniepoint", "OPay", "PalmPay"],
  },
  {
    careerId: "cloud_architect",
    title: "Cloud Architect",
    category: "Technology",
    description:
      "Design and oversee cloud computing strategies and infrastructure.",
    demandLevel: "Very High",
    averageSalary: { entry: 2400000, mid: 7200000, senior: 18000000 },
    growthRate: 28,
    jobOpenings: 1500,
    trending: true,
    remote: true,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "AWS", importance: 10 },
      { name: "Azure", importance: 9 },
      { name: "Microservices", importance: 9 },
      { name: "Security", importance: 9 },
      { name: "Networking", importance: 8 },
      { name: "Terraform", importance: 8 },
    ],
    companies: ["Andela", "Flutterwave", "MTN Nigeria", "Airtel Nigeria", "Interswitch"],
  },
  {
    careerId: "ai_engineer",
    title: "AI/ML Engineer",
    category: "Data & AI",
    description:
      "Design, build, and deploy AI and machine learning systems at scale.",
    demandLevel: "Very High",
    averageSalary: { entry: 2400000, mid: 7200000, senior: 20400000 },
    growthRate: 40,
    jobOpenings: 2000,
    trending: true,
    remote: true,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Python", importance: 10 },
      { name: "TensorFlow", importance: 9 },
      { name: "PyTorch", importance: 9 },
      { name: "MLOps", importance: 8 },
      { name: "Deep Learning", importance: 10 },
      { name: "Mathematics", importance: 9 },
    ],
    companies: ["uLesson", "Andela", "Konga", "Flutterwave", "ThriveAgric"],
  },
  {
    careerId: "data_analyst",
    title: "Data Analyst",
    category: "Data & AI",
    description:
      "Collect, process, and analyze data to generate actionable business insights.",
    demandLevel: "High",
    averageSalary: { entry: 1200000, mid: 3000000, senior: 7200000 },
    growthRate: 23,
    jobOpenings: 6000,
    trending: true,
    remote: true,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "SQL", importance: 10 },
      { name: "Excel", importance: 9 },
      { name: "Python", importance: 8 },
      { name: "Power BI", importance: 8 },
      { name: "Data Visualization", importance: 9 },
      { name: "Statistics", importance: 8 },
    ],
    companies: ["GTBank", "Access Bank", "Zenith Bank", "First Bank", "UBA"],
  },
  {
    careerId: "blockchain_developer",
    title: "Blockchain Developer",
    category: "Technology",
    description:
      "Build decentralized applications and smart contracts on blockchain platforms.",
    demandLevel: "Medium",
    averageSalary: { entry: 2000000, mid: 6000000, senior: 15000000 },
    growthRate: 30,
    jobOpenings: 800,
    trending: true,
    remote: true,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Solidity", importance: 10 },
      { name: "Web3.js", importance: 9 },
      { name: "JavaScript", importance: 8 },
      { name: "Cryptography", importance: 8 },
      { name: "Smart Contracts", importance: 10 },
      { name: "Ethereum", importance: 9 },
    ],
    companies: ["Binance Nigeria", "Luno", "Patricia", "Quidax", "Yellow Card"],
  },

  // ── MEDICAL & HEALTH ────────────────────────────────────────────────────────
  {
    careerId: "physician",
    title: "Physician / Medical Doctor",
    category: "Medical & Health",
    description:
      "Diagnose and treat illnesses, combining scientific knowledge with compassionate patient care.",
    demandLevel: "Very High",
    averageSalary: { entry: 3600000, mid: 9600000, senior: 24000000 },
    growthRate: 13,
    jobOpenings: 25000,
    trending: true,
    remote: false,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Clinical Diagnosis", importance: 10 },
      { name: "Patient Care", importance: 10 },
      { name: "Pharmacology", importance: 9 },
      { name: "Anatomy", importance: 9 },
      { name: "Medical Ethics", importance: 8 },
      { name: "Communication", importance: 9 },
    ],
    companies: [
      "Lagos University Teaching Hospital",
      "National Hospital Abuja",
      "Eko Hospital",
      "Reddington Hospital",
      "St. Nicholas Hospital",
    ],
  },
  {
    careerId: "nurse",
    title: "Registered Nurse",
    category: "Medical & Health",
    description:
      "Provide and coordinate patient care and offer advice and support to patients and families.",
    demandLevel: "Very High",
    averageSalary: { entry: 1200000, mid: 2400000, senior: 4800000 },
    growthRate: 15,
    jobOpenings: 45000,
    trending: true,
    remote: false,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Patient Care", importance: 10 },
      { name: "Clinical Assessment", importance: 10 },
      { name: "Medication Administration", importance: 9 },
      { name: "Critical Thinking", importance: 9 },
      { name: "Communication", importance: 9 },
      { name: "Electronic Health Records", importance: 7 },
    ],
    companies: [
      "Lagos University Teaching Hospital",
      "Federal Medical Centre",
      "Eko Hospital",
      "Lagoon Hospital",
      "Kelina Hospital",
    ],
  },
  {
    careerId: "pharmacist",
    title: "Pharmacist",
    category: "Medical & Health",
    description:
      "Dispense medications, counsel patients on drug use, and collaborate with healthcare teams.",
    demandLevel: "High",
    averageSalary: { entry: 2400000, mid: 4800000, senior: 9600000 },
    growthRate: 6,
    jobOpenings: 8000,
    trending: false,
    remote: false,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Pharmacology", importance: 10 },
      { name: "Drug Interactions", importance: 10 },
      { name: "Patient Counseling", importance: 9 },
      { name: "Chemistry", importance: 8 },
      { name: "Regulatory Compliance", importance: 8 },
      { name: "Clinical Pharmacy", importance: 9 },
    ],
    companies: [
      "Fidson Healthcare",
      "May & Baker Nigeria",
      "GSK Nigeria",
      "Emzor Pharmaceuticals",
      "Neimeth International",
    ],
  },
  {
    careerId: "public_health_specialist",
    title: "Public Health Specialist",
    category: "Medical & Health",
    description:
      "Promote community health, design prevention programs, and analyze population health data.",
    demandLevel: "High",
    averageSalary: { entry: 1500000, mid: 3000000, senior: 6000000 },
    growthRate: 14,
    jobOpenings: 5000,
    trending: true,
    remote: true,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Epidemiology", importance: 10 },
      { name: "Biostatistics", importance: 9 },
      { name: "Data Analysis", importance: 8 },
      { name: "Public Health Policy", importance: 9 },
      { name: "Community Outreach", importance: 8 },
      { name: "Grant Writing", importance: 7 },
    ],
    companies: [
      "Nigeria Centre for Disease Control",
      "WHO Nigeria",
      "UNICEF Nigeria",
      "Federal Ministry of Health",
      "Clinton Health Access Initiative",
    ],
  },
  {
    careerId: "medical_researcher",
    title: "Medical / Biomedical Researcher",
    category: "Medical & Health",
    description:
      "Conduct research to advance medical knowledge and develop new treatments.",
    demandLevel: "High",
    averageSalary: { entry: 2000000, mid: 4200000, senior: 9000000 },
    growthRate: 17,
    jobOpenings: 2000,
    trending: true,
    remote: false,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Research Methods", importance: 10 },
      { name: "Statistics", importance: 9 },
      { name: "Laboratory Techniques", importance: 9 },
      { name: "Scientific Writing", importance: 9 },
      { name: "Python", importance: 7 },
      { name: "Clinical Trials", importance: 8 },
    ],
    companies: [
      "Nigerian Institute of Medical Research",
      "University of Lagos",
      "University of Ibadan",
      "Covenant University",
      "Lagos State University",
    ],
  },

  // ── FINANCE & ECONOMICS ─────────────────────────────────────────────────────
  {
    careerId: "financial_analyst",
    title: "Financial Analyst",
    category: "Finance & Economics",
    description:
      "Evaluate investment opportunities and financial data to guide business decisions.",
    demandLevel: "High",
    averageSalary: { entry: 1500000, mid: 3600000, senior: 7200000 },
    growthRate: 9,
    jobOpenings: 7000,
    trending: false,
    remote: true,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Financial Modeling", importance: 10 },
      { name: "Excel", importance: 10 },
      { name: "Valuation", importance: 9 },
      { name: "Accounting", importance: 8 },
      { name: "Python", importance: 7 },
      { name: "Bloomberg Terminal", importance: 8 },
    ],
    companies: [
      "Stanbic IBTC",
      "United Capital",
      "FBNQuest",
      "Chapel Hill Denham",
      "Coronation Merchant Bank",
    ],
  },
  {
    careerId: "investment_banker",
    title: "Investment Banker",
    category: "Finance & Economics",
    description:
      "Advise corporations on mergers, acquisitions, IPOs, and capital raising strategies.",
    demandLevel: "High",
    averageSalary: { entry: 2400000, mid: 6000000, senior: 18000000 },
    growthRate: 10,
    jobOpenings: 2000,
    trending: true,
    remote: false,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Financial Modeling", importance: 10 },
      { name: "M&A Analysis", importance: 9 },
      { name: "Valuation", importance: 10 },
      { name: "Excel", importance: 9 },
      { name: "Deal Structuring", importance: 9 },
      { name: "Presentation Skills", importance: 8 },
    ],
    companies: [
      "Vetiva Capital",
      "Cardinalstone Partners",
      "United Capital",
      "FBNQuest",
      "Stanbic IBTC",
    ],
  },
  {
    careerId: "accountant",
    title: "Accountant / CPA",
    category: "Finance & Economics",
    description:
      "Prepare and examine financial records, ensure accuracy, and maintain compliance with laws.",
    demandLevel: "High",
    averageSalary: { entry: 1200000, mid: 2400000, senior: 4800000 },
    growthRate: 7,
    jobOpenings: 18000,
    trending: false,
    remote: true,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Bookkeeping", importance: 9 },
      { name: "Tax Preparation", importance: 9 },
      { name: "Financial Reporting", importance: 10 },
      { name: "Excel", importance: 9 },
      { name: "QuickBooks", importance: 8 },
      { name: "Auditing", importance: 8 },
    ],
    companies: ["Deloitte Nigeria", "PwC Nigeria", "EY Nigeria", "KPMG Nigeria", "BDO Nigeria"],
  },
  {
    careerId: "risk_manager",
    title: "Risk Manager",
    category: "Finance & Economics",
    description:
      "Identify, assess, and mitigate financial and operational risks within organizations.",
    demandLevel: "High",
    averageSalary: { entry: 1800000, mid: 3600000, senior: 7200000 },
    growthRate: 11,
    jobOpenings: 3500,
    trending: false,
    remote: true,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Risk Assessment", importance: 10 },
      { name: "Financial Analysis", importance: 9 },
      { name: "Statistics", importance: 9 },
      { name: "Compliance", importance: 8 },
      { name: "Python", importance: 7 },
      { name: "Scenario Analysis", importance: 8 },
    ],
    companies: [
      "Access Bank",
      "Zenith Bank",
      "First Bank",
      "GTBank",
      "Fidelity Bank",
    ],
  },

  // ── ARTS & HUMANITIES ───────────────────────────────────────────────────────
  {
    careerId: "graphic_designer",
    title: "Graphic Designer",
    category: "Arts & Humanities",
    description:
      "Create visual content to communicate messages through typography, imagery, and layout.",
    demandLevel: "High",
    averageSalary: { entry: 800000, mid: 1800000, senior: 4000000 },
    growthRate: 11,
    jobOpenings: 6000,
    trending: false,
    remote: true,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Adobe Photoshop", importance: 10 },
      { name: "Adobe Illustrator", importance: 10 },
      { name: "Typography", importance: 9 },
      { name: "Color Theory", importance: 8 },
      { name: "Branding", importance: 8 },
      { name: "Figma", importance: 8 },
    ],
    companies: ["Noah's Ark", "X3M Ideas", "SO&U", "Insight Publicis", "DDB Lagos"],
  },
  {
    careerId: "content_writer",
    title: "Content Writer / Copywriter",
    category: "Arts & Humanities",
    description:
      "Create compelling written content for digital platforms, marketing, and brand communication.",
    demandLevel: "High",
    averageSalary: { entry: 600000, mid: 1500000, senior: 3600000 },
    growthRate: 9,
    jobOpenings: 8000,
    trending: false,
    remote: true,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Writing", importance: 10 },
      { name: "SEO", importance: 9 },
      { name: "Content Strategy", importance: 9 },
      { name: "Research", importance: 8 },
      { name: "Storytelling", importance: 9 },
      { name: "Editing", importance: 8 },
    ],
    companies: [
      "Stears",
      "Nairametrics",
      "Pulse Nigeria",
      "The Cable",
      "Zikoko",
    ],
  },
  {
    careerId: "journalist",
    title: "Journalist / Reporter",
    category: "Arts & Humanities",
    description:
      "Investigate, report, and present news stories across print, digital, broadcast, and multimedia platforms.",
    demandLevel: "Medium",
    averageSalary: { entry: 800000, mid: 1500000, senior: 3000000 },
    growthRate: 3,
    jobOpenings: 3000,
    trending: false,
    remote: true,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Writing", importance: 10 },
      { name: "Investigative Research", importance: 10 },
      { name: "Interviewing", importance: 9 },
      { name: "Storytelling", importance: 9 },
      { name: "Media Ethics", importance: 8 },
      { name: "Social Media", importance: 7 },
    ],
    companies: ["Channels Television", "TVC News", "The Punch", "Vanguard", "ThisDay"],
  },
  {
    careerId: "teacher_educator",
    title: "Teacher / Educator",
    category: "Education",
    description:
      "Educate students at various levels, developing curriculum and engaging learning environments.",
    demandLevel: "High",
    averageSalary: { entry: 600000, mid: 1200000, senior: 2400000 },
    growthRate: 7,
    jobOpenings: 35000,
    trending: false,
    remote: false,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Curriculum Development", importance: 10 },
      { name: "Classroom Management", importance: 9 },
      { name: "Communication", importance: 10 },
      { name: "Assessment", importance: 8 },
      { name: "Lesson Planning", importance: 9 },
      { name: "EdTech", importance: 7 },
    ],
    companies: [
      "uLesson",
      "Prepclass",
      "Edves",
      "SchoolDrive",
      "Passnownow",
    ],
  },
  {
    careerId: "translator",
    title: "Translator / Interpreter",
    category: "Arts & Humanities",
    description:
      "Convert written or spoken content between languages, preserving meaning and cultural nuance.",
    demandLevel: "Medium",
    averageSalary: { entry: 800000, mid: 1500000, senior: 3000000 },
    growthRate: 6,
    jobOpenings: 1500,
    trending: false,
    remote: true,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Bilingualism", importance: 10 },
      { name: "Cultural Awareness", importance: 9 },
      { name: "Writing", importance: 9 },
      { name: "Research", importance: 8 },
      { name: "CAT Tools", importance: 7 },
      { name: "Attention to Detail", importance: 9 },
    ],
    companies: [
      "United Nations Nigeria",
      "African Development Bank",
      "ECOWAS",
      "AU Nigeria Office",
      "British Council Nigeria",
    ],
  },

  // ── ENGINEERING ─────────────────────────────────────────────────────────────
  {
    careerId: "civil_engineer",
    title: "Civil Engineer",
    category: "Engineering",
    description:
      "Design, build, and maintain infrastructure such as roads, bridges, and water systems.",
    demandLevel: "High",
    averageSalary: { entry: 1500000, mid: 3000000, senior: 7200000 },
    growthRate: 8,
    jobOpenings: 12000,
    trending: false,
    remote: false,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "AutoCAD", importance: 10 },
      { name: "Structural Analysis", importance: 10 },
      { name: "Project Management", importance: 9 },
      { name: "Mathematics", importance: 9 },
      { name: "Building Codes", importance: 8 },
      { name: "BIM", importance: 8 },
    ],
    companies: ["Julius Berger", "Dangote Group", "Reynolds Construction", "CCECC", "Arab Contractors"],
  },
  {
    careerId: "mechanical_engineer",
    title: "Mechanical Engineer",
    category: "Engineering",
    description:
      "Design and develop mechanical systems, machines, and devices from concept to production.",
    demandLevel: "High",
    averageSalary: { entry: 1500000, mid: 3000000, senior: 6000000 },
    growthRate: 7,
    jobOpenings: 8000,
    trending: false,
    remote: false,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "CAD Design", importance: 10 },
      { name: "Thermodynamics", importance: 9 },
      { name: "Mechanics", importance: 10 },
      { name: "Materials Science", importance: 8 },
      { name: "SolidWorks", importance: 9 },
      { name: "MATLAB", importance: 7 },
    ],
    companies: ["NNPC", "Dangote Group", "Flour Mills Nigeria", "Nestlé Nigeria", "Unilever Nigeria"],
  },
  {
    careerId: "electrical_engineer",
    title: "Electrical Engineer",
    category: "Engineering",
    description:
      "Design, develop, and test electrical systems and components for consumer and industrial applications.",
    demandLevel: "High",
    averageSalary: { entry: 1500000, mid: 3600000, senior: 8400000 },
    growthRate: 11,
    jobOpenings: 9000,
    trending: true,
    remote: false,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Circuit Design", importance: 10 },
      { name: "Electronics", importance: 10 },
      { name: "MATLAB", importance: 8 },
      { name: "Signal Processing", importance: 9 },
      { name: "PCB Design", importance: 8 },
      { name: "Embedded Systems", importance: 8 },
    ],
    companies: ["EKEDC", "IKEDC", "Total Energies Nigeria", "MTN Nigeria", "Airtel Nigeria"],
  },
  {
    careerId: "environmental_engineer",
    title: "Environmental Engineer",
    category: "Engineering",
    description:
      "Apply engineering principles to solve environmental problems, including pollution control.",
    demandLevel: "High",
    averageSalary: { entry: 1200000, mid: 2400000, senior: 5400000 },
    growthRate: 12,
    jobOpenings: 4000,
    trending: true,
    remote: false,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Environmental Regulations", importance: 10 },
      { name: "Data Analysis", importance: 8 },
      { name: "Project Management", importance: 9 },
      { name: "Chemistry", importance: 9 },
      { name: "GIS", importance: 8 },
      { name: "Water Treatment", importance: 8 },
    ],
    companies: ["NESREA", "Total Energies Nigeria", "NNPC", "Shell Nigeria", "Chevron Nigeria"],
  },

  // ── BUSINESS & MANAGEMENT ───────────────────────────────────────────────────
  {
    careerId: "marketing_manager",
    title: "Marketing Manager",
    category: "Business & Management",
    description:
      "Plan and execute marketing strategies and brand initiatives to drive growth.",
    demandLevel: "High",
    averageSalary: { entry: 1200000, mid: 3000000, senior: 6000000 },
    growthRate: 10,
    jobOpenings: 7000,
    trending: true,
    remote: true,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Marketing Strategy", importance: 10 },
      { name: "Digital Marketing", importance: 9 },
      { name: "SEO/SEM", importance: 9 },
      { name: "Analytics", importance: 8 },
      { name: "Content Creation", importance: 8 },
      { name: "Brand Management", importance: 9 },
    ],
    companies: ["Unilever Nigeria", "Nestle Nigeria", "MTN Nigeria", "Airtel Nigeria", "Dangote Group"],
  },
  {
    careerId: "human_resources_manager",
    title: "Human Resources Manager",
    category: "Business & Management",
    description:
      "Oversee recruitment, employee relations, benefits, and organizational development.",
    demandLevel: "High",
    averageSalary: { entry: 1200000, mid: 2400000, senior: 4800000 },
    growthRate: 9,
    jobOpenings: 5000,
    trending: false,
    remote: true,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Recruitment", importance: 10 },
      { name: "Employee Relations", importance: 9 },
      { name: "HR Policy", importance: 9 },
      { name: "Communication", importance: 10 },
      { name: "Conflict Resolution", importance: 8 },
      { name: "People Analytics", importance: 7 },
    ],
    companies: ["Andela", "Flutterwave", "MTN Nigeria", "Access Bank", "GTBank"],
  },

  // ── LAW ─────────────────────────────────────────────────────────────────────
  {
    careerId: "lawyer",
    title: "Lawyer / Solicitor",
    category: "Law",
    description:
      "Advise clients on legal matters, draft contracts, and represent them in court or negotiations.",
    demandLevel: "High",
    averageSalary: { entry: 1500000, mid: 3600000, senior: 12000000 },
    growthRate: 9,
    jobOpenings: 6000,
    trending: false,
    remote: false,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Legal Research", importance: 10 },
      { name: "Legal Writing", importance: 10 },
      { name: "Argumentation", importance: 9 },
      { name: "Contract Law", importance: 9 },
      { name: "Critical Thinking", importance: 9 },
      { name: "Negotiation", importance: 8 },
    ],
    companies: [
      "Aelex",
      "Aluko & Oyebode",
      "Banwo & Ighodalo",
      "Templars",
      "Streamsowers & Köhn",
    ],
  },
];

const EXTENDED_MARKET_DATA = [
  {
    careerId: "business_analyst",
    title: "Business Analyst",
    category: "Business & Management",
    description:
      "Analyze business requirements, map processes, and translate needs into actionable product and technical plans.",
    demandLevel: "High",
    averageSalary: { entry: 1500000, mid: 3600000, senior: 7800000 },
    growthRate: 13,
    jobOpenings: 5200,
    trending: true,
    remote: true,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Requirements Analysis", importance: 10 },
      { name: "Process Mapping", importance: 9 },
      { name: "Stakeholder Management", importance: 9 },
      { name: "SQL", importance: 7 },
      { name: "Data Visualization", importance: 8 },
      { name: "Documentation", importance: 8 },
    ],
    companies: ["Interswitch", "Flutterwave", "Andela", "MTN Nigeria", "Moniepoint"],
  },
  {
    careerId: "qa_engineer",
    title: "QA Engineer",
    category: "Technology",
    description:
      "Ensure product quality through structured testing, automation, and release readiness checks.",
    demandLevel: "High",
    averageSalary: { entry: 1200000, mid: 3000000, senior: 6600000 },
    growthRate: 15,
    jobOpenings: 4300,
    trending: true,
    remote: true,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Test Planning", importance: 9 },
      { name: "Selenium", importance: 8 },
      { name: "API Testing", importance: 9 },
      { name: "Cypress", importance: 8 },
      { name: "Bug Tracking", importance: 8 },
      { name: "CI/CD", importance: 7 },
    ],
    companies: ["Paystack", "Kuda", "Termii", "TeamApt", "PiggyVest"],
  },
  {
    careerId: "sales_manager",
    title: "Sales Manager",
    category: "Business & Management",
    description:
      "Lead sales teams, design revenue strategy, and grow pipelines across B2B and B2C channels.",
    demandLevel: "High",
    averageSalary: { entry: 1200000, mid: 2800000, senior: 7200000 },
    growthRate: 12,
    jobOpenings: 9100,
    trending: true,
    remote: false,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Negotiation", importance: 10 },
      { name: "CRM", importance: 8 },
      { name: "Pipeline Management", importance: 9 },
      { name: "Communication", importance: 10 },
      { name: "Forecasting", importance: 8 },
      { name: "Leadership", importance: 9 },
    ],
    companies: ["Airtel Nigeria", "MTN Nigeria", "Dangote Group", "Jumia", "Nestle Nigeria"],
  },
  {
    careerId: "supply_chain_manager",
    title: "Supply Chain Manager",
    category: "Operations",
    description:
      "Optimize procurement, warehousing, and distribution to improve service levels and costs.",
    demandLevel: "High",
    averageSalary: { entry: 1800000, mid: 3600000, senior: 8400000 },
    growthRate: 11,
    jobOpenings: 4700,
    trending: false,
    remote: false,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Logistics", importance: 10 },
      { name: "Inventory Management", importance: 9 },
      { name: "Procurement", importance: 9 },
      { name: "ERP Systems", importance: 8 },
      { name: "Analytics", importance: 7 },
      { name: "Vendor Management", importance: 8 },
    ],
    companies: ["Dangote Group", "Unilever Nigeria", "Flour Mills Nigeria", "Nestle Nigeria", "Jumia"],
  },
  {
    careerId: "customer_success_manager",
    title: "Customer Success Manager",
    category: "Business & Management",
    description:
      "Drive customer retention and account growth through onboarding, product adoption, and strategic support.",
    demandLevel: "High",
    averageSalary: { entry: 1200000, mid: 3000000, senior: 6600000 },
    growthRate: 18,
    jobOpenings: 3900,
    trending: true,
    remote: true,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Relationship Management", importance: 10 },
      { name: "Product Knowledge", importance: 9 },
      { name: "Communication", importance: 10 },
      { name: "Data Analysis", importance: 7 },
      { name: "CRM", importance: 8 },
      { name: "Renewal Strategy", importance: 8 },
    ],
    companies: ["Paystack", "Flutterwave", "Hubtel", "Moniepoint", "Andela"],
  },
  {
    careerId: "dentist",
    title: "Dentist",
    category: "Medical & Health",
    description:
      "Diagnose and treat oral health conditions, and perform preventive and restorative dental procedures.",
    demandLevel: "High",
    averageSalary: { entry: 2400000, mid: 6000000, senior: 12000000 },
    growthRate: 8,
    jobOpenings: 2400,
    trending: false,
    remote: false,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Oral Diagnosis", importance: 10 },
      { name: "Patient Care", importance: 9 },
      { name: "Dental Procedures", importance: 10 },
      { name: "Infection Control", importance: 9 },
      { name: "Communication", importance: 8 },
      { name: "Medical Ethics", importance: 8 },
    ],
    companies: ["Lagos University Teaching Hospital", "Reddington Hospital", "St. Nicholas Hospital", "Eko Dental Clinic", "Smile 360"],
  },
  {
    careerId: "physiotherapist",
    title: "Physiotherapist",
    category: "Medical & Health",
    description:
      "Help patients recover mobility and function through targeted therapy plans and rehabilitation programs.",
    demandLevel: "High",
    averageSalary: { entry: 1500000, mid: 3000000, senior: 6600000 },
    growthRate: 14,
    jobOpenings: 3100,
    trending: true,
    remote: false,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Rehabilitation", importance: 10 },
      { name: "Patient Assessment", importance: 9 },
      { name: "Exercise Therapy", importance: 9 },
      { name: "Communication", importance: 8 },
      { name: "Anatomy", importance: 8 },
      { name: "Care Planning", importance: 8 },
    ],
    companies: ["National Orthopaedic Hospital", "LUTH", "Evercare Hospital", "Eko Hospital", "Hygeia HMO"],
  },
  {
    careerId: "architect",
    title: "Architect",
    category: "Engineering",
    description:
      "Plan and design buildings and spaces that are functional, safe, and sustainable.",
    demandLevel: "Medium",
    averageSalary: { entry: 1200000, mid: 3000000, senior: 7800000 },
    growthRate: 9,
    jobOpenings: 2100,
    trending: false,
    remote: true,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Architectural Design", importance: 10 },
      { name: "AutoCAD", importance: 9 },
      { name: "Revit", importance: 8 },
      { name: "3D Visualization", importance: 8 },
      { name: "Building Codes", importance: 8 },
      { name: "Project Coordination", importance: 8 },
    ],
    companies: ["Julius Berger", "CCECC", "Design Group Nigeria", "ArchiView", "Elalan Construction"],
  },
  {
    careerId: "biotechnologist",
    title: "Biotechnologist",
    category: "Science & Research",
    description:
      "Apply biological science to develop products and processes in health, agriculture, and industry.",
    demandLevel: "Medium",
    averageSalary: { entry: 1500000, mid: 3600000, senior: 7800000 },
    growthRate: 16,
    jobOpenings: 1500,
    trending: true,
    remote: false,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Molecular Biology", importance: 10 },
      { name: "Laboratory Techniques", importance: 9 },
      { name: "Data Analysis", importance: 7 },
      { name: "Research Methods", importance: 9 },
      { name: "Scientific Writing", importance: 8 },
      { name: "Quality Control", importance: 8 },
    ],
    companies: ["Nigerian Institute of Medical Research", "IITA", "NOTAP", "Biovaccines Nigeria", "NABDA"],
  },
  {
    careerId: "game_developer",
    title: "Game Developer",
    category: "Technology",
    description:
      "Build interactive game experiences across mobile, desktop, and web platforms.",
    demandLevel: "Medium",
    averageSalary: { entry: 1500000, mid: 3600000, senior: 9000000 },
    growthRate: 20,
    jobOpenings: 1200,
    trending: true,
    remote: true,
    region: "Nigeria",
    currency: "NGN",
    topSkills: [
      { name: "Unity", importance: 10 },
      { name: "C#", importance: 9 },
      { name: "Game Design", importance: 9 },
      { name: "3D Math", importance: 8 },
      { name: "Debugging", importance: 8 },
      { name: "Version Control", importance: 7 },
    ],
    companies: ["Maliyo Games", "Gamsole", "Kuluya", "ChopUp", "Dimension11"],
  },
];

const seedDB = async () => {
  try {
    await mongoose.connect(
      process.env.MONGO_URI || "mongodb://localhost:27017/ai_career_guidance",
    );
    console.log("Connected to MongoDB");

    const allMarketData = [...MARKET_DATA, ...EXTENDED_MARKET_DATA];

    // Seed market data
    for (const data of allMarketData) {
      await MarketData.findOneAndUpdate(
        { careerId: data.careerId },
        { $set: data },
        { upsert: true },
      );
    }
    console.log(`✅ Seeded ${allMarketData.length} career market records`);

    // Create default admin
    const adminExists = await User.findOne({
      email: "admin@careerguidance.ai",
    });
    if (!adminExists) {
      await User.create({
        name: "Admin User",
        email: "admin@careerguidance.ai",
        password: "Admin@1234",
        role: "admin",
      });
      console.log(
        "✅ Created default admin: admin@careerguidance.ai / Admin@1234",
      );
    }

    console.log("✅ Database seeding complete");
    process.exit(0);
  } catch (error) {
    console.error("Seeding failed:", error);
    process.exit(1);
  }
};

seedDB();
